### Machine Learning Libraries

#### Numpy (Numerical python)
#### Pandas (Data frame - Excel, CSV, table of any form)
#### Matplotlib (Visualization)
#### Seaborn (Visua)
#### Sklearn (Algorithm / Data Processing)
#### Scipy (Statistical)

In [4]:
import numpy as np

In [11]:
simple_list = [1, 2, 3]
np.array(simple_list)

array([1, 2, 3])

In [12]:
arr = np.array([1, 3, 5])
arr

array([1, 3, 5])

In [13]:
matrix = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
np.array(matrix)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [14]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [16]:
np.arange(1, 100, 5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [18]:
np.zeros(10, dtype = bool)

array([False, False, False, False, False, False, False, False, False,
       False])

In [20]:
np.ones(6, dtype = int)

array([1, 1, 1, 1, 1, 1])

In [21]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [23]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [24]:
np.eye(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [25]:
np.random.rand(2, 4)

array([[0.51739448, 0.49913312, 0.76526371, 0.72294863],
       [0.70735469, 0.23111124, 0.43409375, 0.02562976]])

In [27]:
np.random.randn(4, 5)

array([[ 0.10724848,  0.46463761, -0.51101596,  0.43973414,  2.06828318],
       [ 0.02579296, -1.424075  , -0.7379381 , -0.07759948,  1.51986651],
       [ 1.29863808,  0.42144805, -0.11291152,  0.8573352 , -0.97666745],
       [ 0.43157805,  0.40415098, -1.04484038,  1.02415449, -0.82211382]])

In [32]:
np.random.randint(0, 10, 100)

array([3, 8, 1, 1, 7, 4, 4, 1, 2, 1, 5, 1, 9, 8, 7, 8, 8, 3, 8, 9, 3, 4,
       4, 6, 2, 4, 0, 0, 9, 3, 7, 1, 3, 3, 4, 6, 2, 7, 8, 3, 7, 5, 8, 3,
       7, 4, 5, 7, 1, 6, 7, 5, 6, 4, 0, 0, 0, 3, 3, 9, 9, 2, 7, 6, 9, 5,
       4, 1, 8, 7, 8, 1, 8, 3, 3, 3, 8, 0, 6, 0, 1, 4, 0, 3, 7, 6, 4, 5,
       1, 3, 4, 7, 2, 7, 0, 9, 9, 0, 8, 6])

In [37]:
sample_array = np.arange(1, 30)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [54]:
rand_array = np.random.randint(1, 9, 6)
rand_array

array([7, 1, 1, 1, 2, 7])

In [41]:
rand_array.min()

3

In [42]:
rand_array.argmin()

0

In [43]:
rand_array.max()

8

In [44]:
rand_array.argmax()

1

In [47]:
rand_array.dtype

dtype('int32')

In [50]:
a = np.eye(5, dtype = int)
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [51]:
a.T

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [55]:
rand_array.reshape(2, 3)

array([[7, 1, 1],
       [1, 2, 7]])

In [56]:
sample_array = np.arange(1, 10)

In [59]:
sample_array[1:5] = 10
sample_array

array([ 1, 10, 10, 10, 10,  6,  7,  8,  9])

### Two-Dimensional Array

In [65]:
sample_matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
sample_matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [63]:
sample_matrix[1, 2]

7

In [66]:
sample_matrix[:, 2]

array([ 3,  7, 11, 15])

In [67]:
sample_matrix[2, 2]

11

In [69]:
sample_matrix[1:4, 2:4]

array([[ 7,  8],
       [11, 12],
       [15, 16]])

In [70]:
sample_matrix[1:, 2:]

array([[ 7,  8],
       [11, 12],
       [15, 16]])

In [71]:
sample_matrix[2]

array([ 9, 10, 11, 12])

In [72]:
sample_array = np.arange(1, 31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [73]:
sample_array + sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [74]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [75]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [76]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [77]:
np.max(sample_array)

30

In [78]:
np.min(sample_array)

1

In [79]:
np.argmax(sample_array)

29

In [80]:
np.argmin(sample_array)

0

In [81]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900], dtype=int32)

In [82]:
np.std(sample_array)

8.65544144839919

In [83]:
np.mean(sample_array)

15.5

In [84]:
np.var(sample_array)

74.91666666666667

In [85]:
np.random.randn(3, 5)

array([[-1.65861159, -1.38188562,  0.21689503,  0.41995   ,  0.36320065],
       [ 0.22892079, -1.43626473, -0.63731363,  0.02856715,  1.37386877],
       [ 0.31353808, -1.0554187 ,  0.01709216,  0.51326987, -0.07661305]])

In [9]:
Animals = np.array(["Elephant", "Lion", "Cat", "Cat"])
np.unique(Animals)

In [10]:
np.append(Animals, "Dog")

array(['Elephant', 'Lion', 'Cat', 'Cat', 'Dog'], dtype='<U8')